# Generated by Django 4.1.5 on 2023-03-16 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_management', '0003_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='feedback',
            field=models.CharField(max_length=100),
        ),
    ]
