# Generated by Django 4.2.2 on 2023-06-24 12:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emp_management", "0004_alter_feedback_feedback"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testimonial",
            name="rating",
            field=models.IntegerField(),
        ),
    ]
